### ISSUE TITLE
sublime-ui-dark theme

### ISSUE THREAD

**Issue by hassanahmadp** [ryanolsonx/atom-sublime-ui-dark#1]
i have installed this theme but it is not working

**Comment by ryanolsonx** [comment]
I just tested it and it's worked.  Make sure that you set it as your UI Theme.

<img width="1149" alt="Screen Shot 2020-03-23 at 11 15 05 AM" src="https://user-images.githubusercontent.com/238929/77343628-9c1ba200-6cf7-11ea-945a-d3457bf43112.png">
